### ISSUE TITLE
我之前用的是替换ddl方法

### ISSUE THREAD

**Issue by saibancr** [malaohu/reset-navicat-premium#1]
<img width="625" alt="微信图片_20220317142936" src="https://user-images.githubusercontent.com/23053295/158750359-c8cba156-1db0-4a67-bb9b-c8b4ad799d4b.png">
我之前用的是替换ddl方法，现已弃用，您这里说不推荐ddl替换方法感觉挺意味深长的，请问有什么坑吗？

**Comment by malaohu** [comment]
怕里面加料哇。害人之心不可有。
