### ISSUE TITLE
系统找不到指定的注册表项或值。

### ISSUE THREAD

**Issue by xiezehao** [malaohu/reset-navicat-premium#2]
![微信图片_20220325093944](https://user-images.githubusercontent.com/9320056/160037766-010ca7cf-ccb7-44f3-855d-ca16408dd35d.png)

**Comment by coffee0818** [comment]
[version and language]需要自己看注册表替换，比如16XEN，最终这个路径：
echo Delete HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium\Registration16XEN
